name: ci

on:
  - push

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t taehoio/protobuf:${{ github.sha }} \
          --push \
          .
